# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Logs_Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc
from PyQt5.QtWidgets import QTableWidgetItem


class Ui_LogWindow(object):


    def fetch(self):
        mydb = mc.connect(
                host="localhost",
                user="default",
                password="default",
                port="3306",
                database="scraper"
            )
 
        mycursor = mydb.cursor()
 
        mycursor.execute("SELECT * FROM scrpdata ")
 
        result = mycursor.fetchall()
        self.table.setRowCount(0)
        for row_number, row_data in enumerate(result):
            print(row_number)
            self.table.insertRow(row_number)
            for column_number, data in enumerate(row_data):
                #print(column_number)
                self.table.setItem(row_number, column_number, QTableWidgetItem(str(data)))


    def setupUi(self, LogWindow):
        LogWindow.setObjectName("LogWindow")
        LogWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/71066a17509045338985457aa75f9137.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LogWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(LogWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(390, 10, 51, 21))
        self.label.setObjectName("label")
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setGeometry(QtCore.QRect(10, 40, 781, 451))
        self.table.setObjectName("table")
        self.table.setColumnCount(6)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table.setHorizontalHeaderItem(5, item)
        self.refreah_button = QtWidgets.QPushButton(self.centralwidget)
        self.refreah_button.setGeometry(QtCore.QRect(350, 500, 111, 41))
        self.refreah_button.setObjectName("refreah_button")
        self.refreah_button.clicked.connect(self.fetch)
        LogWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LogWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        LogWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LogWindow)
        self.statusbar.setObjectName("statusbar")
        LogWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LogWindow)
        QtCore.QMetaObject.connectSlotsByName(LogWindow)

    def retranslateUi(self, LogWindow):
        _translate = QtCore.QCoreApplication.translate
        LogWindow.setWindowTitle(_translate("LogWindow", "Logs"))
        self.label.setText(_translate("LogWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">LOGS</span></p></body></html>"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("LogWindow", "id"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("LogWindow", "scraper"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("LogWindow", "title"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("LogWindow", "usual price"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("LogWindow", "dropped price"))
        item = self.table.horizontalHeaderItem(5)
        item.setText(_translate("LogWindow", "time&date"))
        self.refreah_button.setText(_translate("LogWindow", "REFRESH"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LogWindow = QtWidgets.QMainWindow()
    ui = Ui_LogWindow()
    ui.setupUi(LogWindow)
    LogWindow.show()
    sys.exit(app.exec_())
