# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainscrn.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    
    def amazon_scraper(self):
        from amazon_main import Ui_AmazonWindow
        #from otherwin import Ui_TestWindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_AmazonWindow()
        self.ui.setupUi(self.window)
        self.window.show()
    #THIS BLOCK CLEARS THE DATA FORM FILES WHICH STORES PRICE OF THE FOLLOWING SCRAPERS
    def amazon_clear(self):
        f = open("GITHUB/amazon_price.csv", "w")
        f.truncate()
        f.close()
        print("amazon data cleared")

    def flipkart_clear(self):
        f = open("GITHUB/flipkart_price.csv", "w")
        f.truncate()
        f.close()
        print("flipkart data cleared")

    def yahoo_clear(self):
        f = open("GITHUB/Yahoo_User.csv", "w")
        f.truncate()
        f.close()
        print("yahoo data cleared")

    
    def flipkart_scraper(self):
        from flipkart_main import Ui_FlipkartWindow
        #from otherwin import Ui_TestWindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_FlipkartWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def yahoo_scraper(self):
        from yahoofin_main import Ui_YahooWindow
        #from otherwin import Ui_TestWindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_YahooWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def content_scraper(self):
        from content_main import Ui_ContentWindow
        #from otherwin import Ui_TestWindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_ContentWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def email_scraper(self):
        from email_main import Ui_EmailWindow
        #from otherwin import Ui_TestWindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_EmailWindow()
        self.ui.setupUi(self.window)
        self.window.show()
    
    def logs(self):
        from logs import Ui_LogWindow
        #from otherwin import Ui_TestWindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_LogWindow()
        self.ui.setupUi(self.window)
        self.window.show()


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1129, 740)
        icon = QtGui.QIcon()
        #change file path to set icon of the window
        icon.addPixmap(QtGui.QPixmap("../../Downloads/71066a17509045338985457aa75f9137.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(480, 0, 191, 91))
        font = QtGui.QFont()
        font.setFamily("Viner Hand ITC")
        self.logo.setFont(font)
        self.logo.setText("")
        #change files path to set logo of window
        self.logo.setPixmap(QtGui.QPixmap("../../Downloads/cc7b052fd3674533a49c3c5d23754ef1.png"))
        self.logo.setScaledContents(False)
        self.logo.setObjectName("logo")
        self.logs_button = QtWidgets.QPushButton(self.centralwidget)
        self.logs_button.setGeometry(QtCore.QRect(1000, 110, 121, 41))
        self.logs_button.setObjectName("logs_button")
        self.logs_button.clicked.connect(self.logs)
        self.running_label = QtWidgets.QLabel(self.centralwidget)
        self.running_label.setGeometry(QtCore.QRect(280, 390, 611, 101))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Light")
        self.running_label.setFont(font)
        self.running_label.setObjectName("running_label")
        self.amazon_label = QtWidgets.QLabel(self.centralwidget)
        self.amazon_label.setGeometry(QtCore.QRect(130, 530, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Swis721 Blk BT")
        font.setBold(False)
        font.setWeight(50)
        self.amazon_label.setFont(font)
        self.amazon_label.setObjectName("amazon_label")
        self.flipkart_label = QtWidgets.QLabel(self.centralwidget)
        self.flipkart_label.setGeometry(QtCore.QRect(130, 580, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Swis721 Blk BT")
        self.flipkart_label.setFont(font)
        self.flipkart_label.setObjectName("flipkart_label")
        self.yahoo_label = QtWidgets.QLabel(self.centralwidget)
        self.yahoo_label.setGeometry(QtCore.QRect(130, 630, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Swis721 Blk BT")
        self.yahoo_label.setFont(font)
        self.yahoo_label.setObjectName("yahoo_label")
        self.email_label = QtWidgets.QLabel(self.centralwidget)
        self.email_label.setGeometry(QtCore.QRect(620, 580, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Swis721 Blk BT")
        self.email_label.setFont(font)
        self.email_label.setObjectName("email_label")
        self.content_label = QtWidgets.QLabel(self.centralwidget)
        self.content_label.setGeometry(QtCore.QRect(630, 530, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Swis721 Blk BT")
        self.content_label.setFont(font)
        self.content_label.setObjectName("content_label")
        self.amazon_button = QtWidgets.QPushButton(self.centralwidget)
        self.amazon_button.setGeometry(QtCore.QRect(490, 530, 93, 28))
        self.amazon_button.setObjectName("amazon_button")
        self.amazon_button.clicked.connect(self.amazon_clear)
        self.flipkart_button = QtWidgets.QPushButton(self.centralwidget)
        self.flipkart_button.setGeometry(QtCore.QRect(490, 580, 93, 28))
        self.flipkart_button.setObjectName("flipkart_button")
        self.flipkart_button.clicked.connect(self.flipkart_clear)
        self.yahoo_button = QtWidgets.QPushButton(self.centralwidget)
        self.yahoo_button.setGeometry(QtCore.QRect(490, 630, 93, 28))
        self.yahoo_button.setObjectName("yahoo_button")
        self.yahoo_button.clicked.connect(self.yahoo_clear)
        self.content_button = QtWidgets.QPushButton(self.centralwidget)
        self.content_button.setGeometry(QtCore.QRect(920, 530, 93, 28))
        self.content_button.setObjectName("content_button")
        self.email_button = QtWidgets.QPushButton(self.centralwidget)
        self.email_button.setGeometry(QtCore.QRect(920, 580, 93, 28))
        self.email_button.setObjectName("email_button")
        self.welcome_label = QtWidgets.QLabel(self.centralwidget)
        self.welcome_label.setGeometry(QtCore.QRect(400, 120, 331, 71))
        self.welcome_label.setObjectName("welcome_label")
        self.to_label = QtWidgets.QLabel(self.centralwidget)
        self.to_label.setGeometry(QtCore.QRect(530, 190, 91, 71))
        self.to_label.setObjectName("to_label")
        self.webscrper_label = QtWidgets.QLabel(self.centralwidget)
        self.webscrper_label.setGeometry(QtCore.QRect(360, 260, 451, 71))
        self.webscrper_label.setObjectName("webscrper_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1129, 26))
        self.menubar.setObjectName("menubar")
        self.menuPrice_Scrapers = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.menuPrice_Scrapers.setFont(font)
        self.menuPrice_Scrapers.setObjectName("menuPrice_Scrapers")
        self.menuContent_Scrapers = QtWidgets.QMenu(self.menubar)
        self.menuContent_Scrapers.setObjectName("menuContent_Scrapers")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAmazon_in = QtWidgets.QAction(MainWindow)
        self.actionAmazon_in.setObjectName("actionAmazon_in")
        self.actionAmazon_in.triggered.connect(self.amazon_scraper)
        self.actionFlipkart_in = QtWidgets.QAction(MainWindow)
        self.actionFlipkart_in.setObjectName("actionFlipkart_in")
        self.actionFlipkart_in.triggered.connect(self.flipkart_scraper)
        self.actionMoneyControl_in = QtWidgets.QAction(MainWindow)
        self.actionMoneyControl_in.setObjectName("actionMoneyControl_in")
        self.actionMoneyControl_in.triggered.connect(self.yahoo_scraper)
        self.actionContent_Scraper = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.actionContent_Scraper.setFont(font)
        self.actionContent_Scraper.setObjectName("actionContent_Scraper")
        self.actionContent_Scraper.triggered.connect(self.content_scraper)
        self.actionEmail_Scraper = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.actionEmail_Scraper.setFont(font)
        self.actionEmail_Scraper.setObjectName("actionEmail_Scraper")
        self.actionEmail_Scraper.triggered.connect(self.email_scraper)
        self.menuPrice_Scrapers.addAction(self.actionAmazon_in)
        self.menuPrice_Scrapers.addAction(self.actionFlipkart_in)
        self.menuPrice_Scrapers.addAction(self.actionMoneyControl_in)
        self.menuContent_Scrapers.addSeparator()
        self.menuContent_Scrapers.addAction(self.actionContent_Scraper)
        self.menuContent_Scrapers.addAction(self.actionEmail_Scraper)
        self.menubar.addAction(self.menuPrice_Scrapers.menuAction())
        self.menubar.addAction(self.menuContent_Scrapers.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.logs_button.setText(_translate("MainWindow", "LOGS"))
        self.running_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600; color:#000000;\">Clear Scrapers</span></p></body></html>"))
        self.amazon_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ff0000;\">Amazon.in_SCRAPER</span></p></body></html>"))
        self.flipkart_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ff0000;\">Flipkart.in_SCRAPER</span></p></body></html>"))
        self.yahoo_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ff0000;\">Yahoo Finance_SCRAPER</span></p></body></html>"))
        self.email_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ff0000;\">Email_SCRAPER</span></p></body></html>"))
        self.content_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ff0000;\">Content_SCRAPER</span></p></body></html>"))
        self.amazon_button.setText(_translate("MainWindow", "CLEAR"))
        self.flipkart_button.setText(_translate("MainWindow", "CLEAR"))
        self.yahoo_button.setText(_translate("MainWindow", "CLEAR"))
        self.content_button.setText(_translate("MainWindow", "CLEAR"))
        self.email_button.setText(_translate("MainWindow", "CLEAR"))
        self.welcome_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600; color:#ff0000;\">WELCOME</span></p></body></html>"))
        self.to_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600;\">TO</span></p></body></html>"))
        self.webscrper_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600; color:#ff0000;\">WEB SCRAPER</span></p></body></html>"))
        self.menuPrice_Scrapers.setTitle(_translate("MainWindow", "Price_Scrapers"))
        self.menuContent_Scrapers.setTitle(_translate("MainWindow", "Other_Scrapers"))
        self.actionAmazon_in.setText(_translate("MainWindow", "Amazon.in"))
        self.actionFlipkart_in.setText(_translate("MainWindow", "Flipkart.in"))
        self.actionMoneyControl_in.setText(_translate("MainWindow", "YahooFinance.in"))
        self.actionContent_Scraper.setText(_translate("MainWindow", "Content_Scraper"))
        self.actionEmail_Scraper.setText(_translate("MainWindow", "Email_Scraper"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
